### ISSUE TITLE
cookie

### ISSUE THREAD

**Issue by sodog01** [nICEnnnnnnnLee/BilibiliLiveRecorder#1]
怎么获取斗鱼的cookie呀？

**Comment by sodog01** [comment]
虎牙貌似不能使用

**Comment by nICEnnnnnnnLee** [comment]
+ 用浏览器打开斗鱼
+ 登录
+ 按`F12`键
![20190825102442](https://user-images.githubusercontent.com/19970934/63644778-19ac0f00-c723-11e9-8f39-eaeaba18f195.png)

+ 选中`网络`，刷新
+ 过滤`www.douyu.com`的URL
+ 随意选择一条请求
+ 把cookie抠出来

**Comment by sodog01** [comment]
加了这个douyu_cookie.txt也是下载不了最高清，获取到的cookie跟你的不一样，你是什么浏览器，我chrome

**Comment by nICEnnnnnnnLee** [comment]
1. `douyu-cookie.txt` √ `douyu_cookie.txt` ×
2. 这个cookie内容和啥浏览器应该没关系哦，`douyu-cookie.txt` 内容示例：
```
dy_did=xxxxxxx; acf_did=xxx; Hm_lvt_xxxxxxxxxxxxxx=xxx; smidV2=xxx; acf_uid=xxx; acf_username=xxx; acf_nickname=xxx; acf_ltkid=xxx; acf_auth=xxx
...太长就不列了
```
3. 如果还不行的话，给个房间id我试试看😳

**Comment by sodog01** [comment]
dy_did=xxxxxxx; acf_did=xxx; Hm_lvt_xxxxxxxxxxxxxx=xxx; smidV2=xxx; acf_uid=xxx; acf_username=xxx; acf_nickname=xxx; acf_ltkid=xxx; acf_auth=xxx，这些内容都要？不是只要dy_did?  您试下100房间号

**Comment by nICEnnnnnnnLee** [comment]
+ cookie里面哪些参数生效没有仔细去试。测试了下，单只有`dy_did`不够
+ 我这边100房间号试了下没问题😳

**Comment by sodog01** [comment]
Hm_lvt_xxxxxxxxxxxxxx=xxx  其他都找到，就这个参数没看到

**Comment by nICEnnnnnnnLee** [comment]
请求的cookie抓全就行。
写的时候直接模拟的浏览器行为，没怎么考虑过cookie各字段含义。
理论上浏览器能看，抠出来的cookie就能下，差不多这个意思吧

**Comment by nICEnnnnnnnLee** [comment]
#7 斗鱼从网页里面提取的清晰度不全，可能有些误导
