### ISSUE TITLE
douyin已经无法使用

### ISSUE THREAD

**Issue by MicroCountry** [nICEnnnnnnnLee/BilibiliLiveRecorder#101]
RoomDealerDouyin-getLiveDataByShortId/183 : {"data":{"prompts":"该内容暂时无法无法查看"},"extra":{"now":1670229880654},"status_code":4001038}

**Comment by nICEnnnnnnnLee** [comment]
请提供直播间ID

**Comment by MicroCountry** [comment]
我通过更改 apiUrl  和 cookie可以解决，这个url好像经常会变

**Comment by nICEnnnnnnnLee** [comment]
可以尝试使用`https://live.douyin.com/30839489393`

![Screenshot 2022-12-05 at 17-02-40 游戏直播💖星星的主页 - 抖音](https://user-images.githubusercontent.com/19970934/205596943-529efd9a-ba86-4778-ab77-ab7c698a3519.png)

**Comment by MicroCountry** [comment]
也不行，我这边需要替换使用目前浏览器打开后完整的token 和 完整的douyin.com/webcast/web/enter/链接，且要带上token 和_signature

**Comment by nICEnnnnnnnLee** [comment]
我不知道你是怎么操作的，也没搞懂你在说什么。    
+ 本项目只涉及：
    + 直播链接提取的**房间ID**
    + 进入具体直播间后过了可能出现的验证码的**完整cookie**
