### ISSUE TITLE
cookie解析失败

### ISSUE THREAD

**Issue by Rinne0** [nICEnnnnnnnLee/BilibiliLiveRecorder#105]
今天刚出现的情况，昨天还没有，尝试任何cookie都没法解析
![QQ截图20230106173620](https://user-images.githubusercontent.com/62037831/210973565-b603cfd7-9b96-487d-adb6-249868e017a7.png)
![image](https://user-images.githubusercontent.com/62037831/210973666-96b03469-c12e-4288-9b43-1e91ef6323a9.png)

**Comment by nICEnnnnnnnLee** [comment]
试试`douyin2`

**Comment by Rinne0** [comment]
![QQ截图20230106223339](https://user-images.githubusercontent.com/62037831/211032933-106c95d8-deb1-4855-8a45-6e5c5ee5e9c4.png)

**Comment by Rinne0** [comment]
它说没有douyin2这个录制器

**Comment by Rinne0** [comment]
![QQ截图20230106223612](https://user-images.githubusercontent.com/62037831/211033399-ca37bcc8-9648-40ad-80fa-ad198bee48e7.png)
下载xinbanben新版本有douyin2了但是还是解析不了cookie，我试了好多抖音的cookie都是解析失败

**Comment by Rinne0** [comment]
![image](https://user-images.githubusercontent.com/62037831/211033618-3dd6c24c-7660-4b76-bf55-4a6a23b00360.png)
不好意思忘记改文本的名字了，改了之后就可以正常用了，但是好像douyin直播源确实出问题了
