### ISSUE TITLE
测试douyin时，发现参数check为false不起效的bug

### ISSUE THREAD

**Issue by HarlockHomes** [nICEnnnnnnnLee/BilibiliLiveRecorder#107]
参数如下： debug=true&check=true&liver=douyin&check=false&delete=false&filePeriod=5&stopAfterOffline=false&retryIfLiveOff=true&maxRetryIfLiveOff=0&retryAfterMinutes=3

check为false，程序还是会耗时进行“插入时间戳”的动作，目录内还是会成 checked文件。
请问应该如何禁止？

**Comment by nICEnnnnnnnLee** [comment]
+ debug=true&**check=true**&liver=douyin&**check=false**&...  
解析传入参数使用的是正则匹配，只会匹配到第一个符合条件的。

**Comment by HarlockHomes** [comment]
啊明白了，多谢多谢。
