### ISSUE TITLE
测试douyin时，录制时按分钟分段，发现后段包含前段尾部重复的几秒，请问如何减少重复至0？

### ISSUE THREAD

**Issue by HarlockHomes** [nICEnnnnnnnLee/BilibiliLiveRecorder#108]
测试douyin时，录制时按分钟分段，发现后段包含前段尾部重复的几秒，请问如何减少重复时间至0？

**Comment by nICEnnnnnnnLee** [comment]
+ 没法准确控制既不重复也不缺漏。
+ 对于重复的部分，理论上可以根据对比两个文件的原始时间戳来去除重复。  
但是本程序没有该功能，也没有计划实现该功能。

**Comment by HarlockHomes** [comment]
对比两个文件的原始时间戳——请问是指checked之前的原始文件，是吗？
据你所知有什么软件带有此功能可以合并时去掉重复？

**Comment by nICEnnnnnnnLee** [comment]
> 对比两个文件的原始时间戳——请问是指checked之前的原始文件，是吗？

是的


 > 据你所知有什么软件带有此功能可以合并时去掉重复？

不知道
