### ISSUE TITLE
直播录制的视频文件格式能否默认是TS文件，flv无法实时预览

### ISSUE THREAD

**Issue by androw02** [nICEnnnnnnnLee/BilibiliLiveRecorder#110]
TS视频文件可以边录制边播放，还不容易录制出错，

**Comment by nICEnnnnnnnLee** [comment]
不采用HLS流是因为没有很好的java库来处理下载完的众多ts文件。  
如非必要，我是不会考虑外部调用ffmpeg等程序的。  
如果你有好的解决办法，欢迎PR。

<hr/>

> flv无法实时预览
> TS视频文件可以边录制边播放

+ 确实可以通过打开单个的ts文件片段来看看下载内容，但也不至于到`可以边录制边播放`的程度，也就确认一下录制是否出了差错。  
而如果只是要简单确认录制内容没有问题的话，可以这么说，只要保证FLV的连接不断开，那就冇问题。

> TS视频还不容易录制出错

都是下载文件，FLV录制很容易出错吗？  
如果你说的是后期处理，像主播PK这种，TS文件一样要进行区分，把分辨率不同的TS片段分开

**Comment by HarlockHomes** [comment]
实时的下载进程中文件，你用potplay播放，是可以实时预览的。
