### ISSUE TITLE
抖音cookie不行

### ISSUE THREAD

**Issue by kcxg** [nICEnnnnnnnLee/BilibiliLiveRecorder#111]
![image](https://user-images.githubusercontent.com/31840413/215251059-04ec9081-fbbb-4d99-b074-4b87d7216f78.png)

![image](https://user-images.githubusercontent.com/31840413/215251107-f18fcc7f-879c-493b-bdc6-6176bde0f4cb.png)

![image](https://user-images.githubusercontent.com/31840413/215251117-e071ff7f-68c8-4ae2-8e5b-45d0d0175223.png)
![image](https://user-images.githubusercontent.com/31840413/215251135-80788245-440b-426f-b931-58b1a5c25ccc.png)

**Comment by nICEnnnnnnnLee** [comment]
从log看，cookie字符串为null，应该是程序没有识别到cookie文件

**Comment by kcxg** [comment]
文件名多加了个 .txt ，已解决，感谢！！
