### ISSUE TITLE
今日运行douyin，遇到报cookie不存在或过期，浏览器里提取更新后还是一样，请问是否有什么变化？

### ISSUE THREAD

**Issue by HarlockHomes** [nICEnnnnnnnLee/BilibiliLiveRecorder#112]
昨天还是好的，今日运行douyin，遇到报cookie不存在或过期，浏览器里提取更新后还是一样，请问是否有什么变化？

**Comment by HarlockHomes** [comment]
刚刚又提取了cookie，这次成功运行了。

**Comment by HarlockHomes** [comment]
对比之下貌似新提取的cookie多了这两个
__ac_nonce=063dc0***********;
 __ac_signature=_02B4Z************

**Comment by charon627** [comment]
今天还可以吗？我这下午开始完全不行，最新版本换了很多次cookie还是报错

**Comment by charon627** [comment]
> 今天还可以吗？我这下午开始完全不行，最新版本换了很多次cookie还是报错

douyin还是不行
RoomDealerDouyin-getLiveDataByShortId/177 : {"data":{"message":"Request params error","prompts":"当前服务繁忙，请稍后重试"},"extra":{"now":1675765510169},"status_code":10011}
org.json.JSONException: JSONObject["user"] not found.

**Comment by hofaeair** [comment]
我也遇到了这个问题
![image](https://user-images.githubusercontent.com/78331871/217259100-06272da5-f89c-4068-89c5-fb8facf9e688.png)

**Comment by nICEnnnnnnnLee** [comment]
👇
![1](https://user-images.githubusercontent.com/19970934/217268124-2d966c07-ad27-4ecc-bd10-a04b6ce73061.png)

![2](https://user-images.githubusercontent.com/19970934/217268147-b095114e-97c0-48f7-a147-ee3e7742b941.png)

**Comment by charon627** [comment]
第4步和set-cookie那什么意思没懂

**Comment by charon627** [comment]
这个需要怎么修改复制后cookie?
