### ISSUE TITLE
请问现在抖音是不是用不了?

### ISSUE THREAD

**Issue by Bloodborne** [nICEnnnnnnnLee/BilibiliLiveRecorder#118]
试过douyin和douyin2，encodeURI()，还有issue里的set-cookie替换。我是用 https://live.douyin.com/webcast/ 这个接口里cookie。一直都是报这个错:
> java.lang.IllegalArgumentException: Illegal cookie name
> 	at java.net.HttpCookie.<init>(HttpCookie.java:145)
> 	at java.net.HttpCookie.<init>(HttpCookie.java:139)
> 	at nicelee.bilibili.util.HttpCookies.convertCookies(HttpCookies.java:16)
> 	at nicelee.bilibili.live.impl.RoomDealerDouyin4User.getRoomInfo(RoomDealerDouyin4User.java:96)
> 	at nicelee.bilibili.Main.getRoomInfo(Main.java:153)
> 	at nicelee.bilibili.Main.main(Main.java:86)
> 抖音需要cookie, 请确认cookie是否存在或失效
> 解析失败！！

**Comment by nICEnnnnnnnLee** [comment]
可以用。  

真的不是很想讨论关于cookie获取的问题，这不是本项目所关注的，顶多就是提一嘴的事儿。     
鉴于很多issue都提到这个，我就讲一下提到过的相关措施，以及为什么要这样做。  


+ 要录制某直播，先浏览器打开该直播间   
当然更通用的做法是从首页进入一个热度高的直播间，并选择能够选的最高清晰度。  
这些没啥好说的。  

+ F12，筛选网址，选择请求，复制Cookie项的值
这只是获取cookie的一种方法，个人认为最快捷，也就提了一下。    
要是有办法获取需要的name、value然后再拼接，也是可以的。

+ 为什么筛选网址时，只提及`https://live.douyin.com/`甚至`www.douyu.com`，而不是更具体一点的链接？  
常见的几乎所有cookie设置的Path都是`/`，所有协议都是`https`，因而只需要确定域名就够了。  
条件更多可能会错过某些请求，漏掉cookie刷新项

+ 为什么说过将cookie在控制台里用encodeURI转一下的话
浏览器它有时候呈现的cookie和抓包不太一致，历史版本处理的时候出了问题。
`ttwid=1%7C0CRNQycblK_U-M2...` √
`ttwid=1|0CRNQycblK_U-M2...` ×

+ 为什么提到  选取最后一项筛选的网络请求，并用`set-cookie`替换掉cookie中对应的值
刚打开直播间时，douyin的msToken失效得非常快，一个api请求过去cookie的msToken值就变了。    
为了确保cookie的值是有效的，我们必须选择最后一条请求。  
而因为这是最后一个请求，所以我们没办法直接复制下一个请求的Cookie项，只能采取复制当前的Cookie项，并`set-cookie`替换的方式。

**Comment by nICEnnnnnnnLee** [comment]
基本上不会有省略号的，你这是复制的时候cookie太长折叠显示了
