### ISSUE TITLE
程序调用时传入参数如何设置，能选择校验文件分割scripts tag

### ISSUE THREAD

**Issue by yslinwe** [nICEnnnnnnnLee/BilibiliLiveRecorder#12]

**Comment by nICEnnnnnnnLee** [comment]
目前虽然实现了这个功能，但是它是作为一种纠错的后备方案存在，**默认的处理仅涉及时间戳校正，尚无配置能自动调用该操作**
  
   
   
 
   
 
   
   
    
    
 
    
 
    
 
   
   
   
    
    
 
   
   
  
 
  
 
   ------------------------原始邮件------------------------  
   
   发信人：yslinwe<notifications@github.com>

 
   时间：04:34:10 上午
 
   收信人：nICEnnnnnnnLee/BilibiliLiveRecorder<bilibililiverecorder@noreply.github.com>

 
   抄送：Subscribed<subscribed@noreply.github.com>

 
   标题：[nICEnnnnnnnLee/BilibiliLiveRecorder] 程序调用时传入参数如何设置，能选择校验文件分割scripts tag (#12)

**Comment by nICEnnnnnnnLee** [comment]
现在的情况是，当录制文件存在多个scripts tag的异常状况时，有可能只有分割后才能正常播放；也有可能不分割可以正常播放，而分割后反而不行。
  
   
   

  
   
   

  
  
    在某些旧版本本来是统一分割处理的，但发现其实也不是很通用，反而增加了还原视频的难度。最后干脆默认纠正时戳删源文件，能对付大多数情况。
  
   
   

  
   
   

  
  
    这个特性可以加到下个版本的TODO list（然而短时间内不会开工🙄另欢迎PR 
   
 
   
 
   
 
   
   
    
    
 
    
 
    
 
   
   
   
    
    
 
   
   
  
 
  
 
   ------------------------原始邮件------------------------  
   
   发信人：yslinwe<notifications@github.com>

 
   时间：04:34:10 上午
 
   收信人：nICEnnnnnnnLee/BilibiliLiveRecorder<bilibililiverecorder@noreply.github.com>

 
   抄送：Subscribed<subscribed@noreply.github.com>

 
   标题：[nICEnnnnnnnLee/BilibiliLiveRecorder] 程序调用时传入参数如何设置，能选择校验文件分割scripts tag (#12)
