### ISSUE TITLE
录制虎牙输入完清晰度直接停止了

### ISSUE THREAD

**Issue by huiye2000** [nICEnnnnnnnLee/BilibiliLiveRecorder#124]
![C9695B7835886C36938B978421D52216](https://github.com/nICEnnnnnnnLee/BilibiliLiveRecorder/assets/85208521/a164b447-e745-4254-bd14-26f46b5087e9)

**Comment by nICEnnnnnnnLee** [comment]
请尝试`liver=huya2`
