### ISSUE TITLE
请问能否支持自定义输出路径或文件名

### ISSUE THREAD

**Issue by m011** [nICEnnnnnnnLee/BilibiliLiveRecorder#13]
请问能否支持参数自定义文件名称或路径，如 &filename=xx5566.flv 或 &filepath=“e:\rec\xx5566.flv”如果参数为空则继续用现在的方案。

**Comment by nICEnnnnnnnLee** [comment]
这个可以考虑，但是需要讨论。
  
   
   

  
   
   

  
  
    当出现分段录制、异常后重新录制、时间戳校准处理或者scripts tag分割时，将会出现若干个文件，这时仅仅指定一个文件名是不够的 
   
 
   
 
   
 
   
   
    
    
 
    
 
    
 
   
   
   
    
    
 
   
   
  
 
  
 
   ------------------------原始邮件------------------------  
   
   发信人：m011<notifications@github.com>

 
   时间：10:51:10 下午
 
   收信人：nICEnnnnnnnLee/BilibiliLiveRecorder<bilibililiverecorder@noreply.github.com>

 
   抄送：Subscribed<subscribed@noreply.github.com>

 
   标题：[nICEnnnnnnnLee/BilibiliLiveRecorder] 请问能否支持自定义输出路径或文件名 (#13)
 
   
  请问能否支持参数自定义文件名称或路径，如 &filename=xx5566.flv 或 &filepath=“e:\rec\xx5566.flv”如果参数为空则继续用现在的方案。

**Comment by m011** [comment]
您看这样行不行，
1，在文件名末尾加上序号，filename_1.flv, filename_2.flv 
2，可以提供些标签让用户自己组合成名称，比如 {shortid} _{roomid}_{starttime}_{sequence}.flv
