### ISSUE TITLE
关于 FlvChecker 和 FlvCheckerWithBufferEx 的疑惑

### ISSUE THREAD

**Issue by Bloodborne** [nICEnnnnnnnLee/BilibiliLiveRecorder#131]
录了一个抖音直播的视频，控制台显示录制了1个小时，但是用播放器打开只有30分钟，进度条拖到最后还会一直播放下去，但是进度条一直卡在最后不会变化，应该是时间戳有问题了。
1. 用这个方法 `java -Dfile.encoding=utf-8 -cp BiliLiveRecorder.jar nicelee.bilibili.live.check.FlvCheckerWithBufferEx "flv=源文件路径&debug=false&splitScripts=true&splitAVHeader=true&saveFolder=保存的文件夹路径"`，切割生成5个文件，但是有2个文件完全播放不了。
2. 将`splitScripts`和`splitAVHeader`设为`false`再次执行上述方法，生成的flv文件依旧和源文件有一样的问题。
3. 使用 https://github.com/nICEnnnnnnnLee/BilibiliLiveRecorder/issues/6#issuecomment-531631899 提到的 ` java -Dfile.encoding=utf-8 -cp BiliLiveRecorder.jar nicelee.bilibili.live.FlvChecker "文件路径"` ，生成的flv文件时长恢复成1小时，能正常播放。

所以有个疑惑，为什么 `FlvCheckerWithBufferEx` 修复不了的视频而 `FlvChecker`  能修复，两者有何区别😂？（源码看不懂，问ai也无法解决😂）
如需视频文件分析的话可以提供。

**Comment by nICEnnnnnnnLee** [comment]
这五个文件的大小分别是多少

**Comment by nICEnnnnnnnLee** [comment]
![Screenshot_2024-04-22-23-53-04-866_com.github.android.jpg](https://github.com/nICEnnnnnnnLee/BilibiliLiveRecorder/assets/19970934/5c3213f2-ee98-4e29-b194-149ccf674ef2)
