### ISSUE TITLE
录制时会有一定几率断开，是网络的锅吗？

### ISSUE THREAD

**Issue by weirdo4253** [nICEnnnnnnnLee/BilibiliLiveRecorder#17]
![2019-12-22_034249](https://user-images.githubusercontent.com/12150840/71318327-6550a880-24ca-11ea-92e5-ef11306b6d42.png)
还有就是希望增加一个强制画质的功能，没有获取到就重新get，我设置的“4-蓝光4M”，但是有几率获取不到就会跳到“0-蓝光10M”。

**Comment by nICEnnnnnnnLee** [comment]
+ 当连接成功建立，断掉的话就应该是网络的锅了😳 ，我是这样认为的
+ 不好意思，我可能没理解描述的`强制画质的功能`？

**Comment by weirdo4253** [comment]
> * 当连接成功建立，断掉的话就应该是网络的锅了😳 ，我是这样认为的
> * 不好意思，我可能没理解描述的`强制画质的功能`？

直播视频清晰度的数值我在命令行里传入的参数是4，但因为刚开播没有这个清晰度，所以按照程序的逻辑会自动选择0开始录制。

希望增加的功能是如果获取到的清晰度没有传入的参数里要求的清晰度就停止程序或者重新获取一遍清晰度。
