### ISSUE TITLE
快手貌似不能正常录制

### ISSUE THREAD

**Issue by aobitiger** [nICEnnnnnnnLee/BilibiliLiveRecorder#19]
快手直播并不向其他平台那样有纯数字的房间号，直播地址后面都是自己的ID，不知道是不是跟这个有关系

**Comment by nICEnnnnnnnLee** [comment]
+ 房间是否是纯数字并不影响功能。
        像 `https://live.kuaishou.com/u/mianf666`， ID为 `mianf666`

+ 如果不能录制，请尝试更换一下cookie（程序嵌入的那个因为最近没咋看快手，有效性没有刷新，不过你看到的这会儿应该已经好了）

**Comment by aobitiger** [comment]
确实已经好了，谢谢答复！真的找遍github也没有这么方便的应用。另外有没有考虑把软件做一个python版？在nas搞java环境貌似比较复杂。
