### ISSUE TITLE
cookie

### ISSUE THREAD

**Issue by sodog01** [nICEnnnnnnnLee/BilibiliLiveRecorder#21]
希望能写下如何正确获取斗鱼的cookie

**Comment by nICEnnnnnnnLee** [comment]
+ 我有注意到在#1 提出了同样的问题，  
当时是从网页里面爬的清晰度，可能因为清晰度选项不全或描述不符#7 ，导致了对cookie的有效性有所疑问。

+ cookie的获取过程如#1 中所示，不再赘述。另在抓取cookie前请确保账号已登录
