### ISSUE TITLE
FlvChecker能否自定义输出目录？

### ISSUE THREAD

**Issue by m011** [nICEnnnnnnnLee/BilibiliLiveRecorder#22]
现在校准时间戳时输出的文件和源文件是同一目录，也就是在同一硬盘上，当文件比较大或同时操作多个文件时IO性能很低，等待时间太长，能否扩展一个参数可以自定义输出目录，这样就可以把读和写分离到不同硬盘上。
谢谢！

**Comment by m011** [comment]
好象只是重载了方法参数，但实际并没有接收参数

**Comment by nICEnnnnnnnLee** [comment]
或许我理解错了你的意思。我重新理解了下，不是自己调用，而是程序加入这个功能

**Comment by m011** [comment]
直接使用 java -Dfile.encoding=utf-8 -cp BiliLiveRecorder.jar nicelee.bilibili.live.FlvChecker "源文件路径" true "保存的文件夹路径"  调用时，还是不支持，没有解析  "保存的文件夹路径"  参数
 if ((args != null) && (args.length >= 2)) {
      splitScripts = "true".equals(args[1]);
    }

**Comment by nICEnnnnnnnLee** [comment]
大写的尴尬😳
