### ISSUE TITLE
能否添加定时执行或未开播重试到开播再执行

### ISSUE THREAD

**Issue by kayleyang** [nICEnnnnnnnLee/BilibiliLiveRecorder#23]
录制直播得去卡点开播时间，希望能够设置如果未开播就等待几分钟后重试几次

**Comment by nICEnnnnnnnLee** [comment]
感觉这部分工作可以在程序外进行啊
----- 原始邮件 -----
发件人：kayleyang <notifications@github.com>
收件人：nICEnnnnnnnLee/BilibiliLiveRecorder <BilibiliLiveRecorder@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[nICEnnnnnnnLee/BilibiliLiveRecorder]_能否添加定时执行或未开播重试到开播再执行_(#23)
日期：2020年01月16日 11点27分

录制直播得去卡点开播时间，希望能够设置如果未开播就等待几分钟后重试几次



&mdash;

**Comment by nICEnnnnnnnLee** [comment]
| Key  | 必选 | 释义 | 
| ------------- | ------------- | ------------- |  
| retryIfLiveOff  | 否 | 当目标不在直播时，是否继续重试。默认false | 
| maxRetryIfLiveOff  | 否 | 当目标不在直播时，继续重试的次数。默认0，此时会一直进行尝试，直到主播上线 | 
| retryAfterMinutes  | 否 | 当目标不在直播时，每次获取直播间信息的时间间隔，单位分钟。默认`5.0` |
