### ISSUE TITLE
[请教作者大佬] bilibili 直播流抓出来后 , 是怎么实现下载的 , 为何抓到的url直接丢到浏览器不能下载

### ISSUE THREAD

**Issue by yoyosnart** [nICEnnnnnnnLee/BilibiliLiveRecorder#24]
如题 , 最近遇到一个问题 , 以前从api爬出url后 , 就可以直接用 webclient 实现下载 , 最近突然不行了 , 服务器直接拒绝返回错误 , 其余的如 ykdl 也遇到同样的问题 , 但比较一下都是使用同一个api爬出的url , 故请教大佬是使用何种方法保存直播源数据的

**Comment by nICEnnnnnnnLee** [comment]
大概直播流服务器反爬，headers出了问题吧。
供参考：
```python
self.download_headers = {
    'Accept': '*/*',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2',
    'Origin': 'https://live.bilibili.com',
    'Referer': 'https://live.bilibili.com/%s'%self.short_id,
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0'
}
```

**Comment by yoyosnart** [comment]
谢大佬 , 我也好蒙阿 , 我用这样的方式请求 , 还是一样 , 直接返回了错误

遠端伺服器傳回一個錯誤: (459) 

`HttpWebRequest request = (HttpWebRequest)WebRequest.Create(uri);

            Uri myUri = new Uri(url);
            string host = myUri.Host;  


            //request.Headers.Clear();
            //request.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;

            CookieContainer cookies = new CookieContainer();
            request.Method = "GET";
            SetHeaderValue(request.Headers, "Accept", "*/*");
            SetHeaderValue(request.Headers, "Accept-Encoding", "gzip, deflate, br");
            SetHeaderValue(request.Headers, "Accept-Language", "zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2");
            //SetHeaderValue(request.Headers, "Connection", "keep-alive");
            SetHeaderValue(request.Headers, "Origin", "https://live.bilibili.com");
            //SetHeaderValue(request.Headers, "Host", "3geauymtsgrzdrcbzfahur.ourdvsss.com");
            SetHeaderValue(request.Headers, "Referer", "https://live.bilibili.com/blanc/" + shortid);
            SetHeaderValue(request.Headers, "User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0");

            request.CookieContainer = cookies;



            try
            {
                using (HttpWebResponse response = (HttpWebResponse)request.GetResponse())
                using (Stream stream = response.GetResponseStream())
                using (StreamReader reader = new StreamReader(stream))
                {
                    return reader.ReadToEnd();
                }
            }
            catch (WebException ex)
            {
                //log("Web Exception Wait 5s");
                return "WebError" + ex.ToString();
            }`

**Comment by nICEnnnnnnnLee** [comment]
+ 可能HTTP请求的工具问题，像`Host`、`Connection`这些也给补上试试    
另外，有些工具不能直接在`headers`里面修饰`Cookie`、`Referer`等字段，你看看有没有专门的`.Referer()/.setReferer()`之类的方法

+ 如果你是录制直播/下载二进制文件的话，建议不要使用`StreamReader`  
    尤其是文件很大的情况下，建议不要使用`.ReadToEnd()`
+ 代码看不出来啥其它问题，本地代理抓一下包，看看你发的这个请求长啥样吧
   下面这个这是浏览器里面的原生的请求：
```
Host: txy.live-play.acgvideo.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: */*
Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Accept-Encoding: gzip, deflate, br
Referer: https://live.bilibili.com/6
Origin: https://live.bilibili.com
Connection: keep-alive
```

**Comment by yoyosnart** [comment]
谢谢大佬 , 我研究研究
