### ISSUE TITLE
音画不同步情况

### ISSUE THREAD

**Issue by ChinaYingXi** [nICEnnnnnnnLee/BilibiliLiveRecorder#27]
在虎牙录制时随着录制时间边长音画不同步情况会出现。
大约在2小时后将会明显出现
check=true

**Comment by nICEnnnnnnnLee** [comment]
+ 这可能是我时间戳优化算法的问题。。。有时间试试换个方式。
+ 目前可以尝试的解决方案：
    + 在录制的时候定时分段录制，基本上不会丢失画面
    + 尝试使用ffmpeg转换一下
