### ISSUE TITLE
经常有花屏的情况 请问怎么解决

### ISSUE THREAD

**Issue by maowayne123** [nICEnnnnnnnLee/BilibiliLiveRecorder#28]

**Comment by nICEnnnnnnnLee** [comment]
请问这个花屏指的是视频最开始的时候，还是在播放的中间？

**Comment by maowayne123** [comment]
> 请问这个花屏指的是视频最开始的时候，还是在播放的中间？
在视频的中间 一花就花个多小时 在高码率录制的时候出现的概率很高 我估计可能是网络波动 丢包 然后把关键帧丢了 但是奇怪的是丢一次帧 视频得过1个多小时才会恢复 很奇怪是什么情况

**Comment by nICEnnnnnnnLee** [comment]
+ 你试一试用分割script tag的方式处理一下视频，看看有没有分成多个文件，打开后是否正常
```
java -Dfile.encoding=utf-8 -cp BiliLiveRecorder.jar nicelee.bilibili.live.FlvChecker "源文件路径" true false
```
+ 如果可以，请先回退到[V2.6.2](https://github.com/nICEnnnnnnnLee/BilibiliLiveRecorder/releases/tag/V2.6.2)，录制的时候传入参数加上`splitScriptTags=true`
