### ISSUE TITLE
希望能支持Linux的信号量机制

### ISSUE THREAD

**Issue by user741852** [nICEnnnnnnnLee/BilibiliLiveRecorder#29]
可以考虑支持信号量。这样一来就能通过sigterm信号停止录制。

**Comment by nICEnnnnnnnLee** [comment]
可以考虑处理 `kill -15` 或者`Ctrl + C`

**Comment by user741852** [comment]
> 可以考虑处理 `kill -15` 或者`Ctrl + C`

这样做的话，后缀名中的part就去不了。

**Comment by nICEnnnnnnnLee** [comment]
抓到信号以后，只要一直阻塞等待录制处理完就好了，
