### ISSUE TITLE
虎牙音频编码问题

### ISSUE THREAD

**Issue by ChinaYingXi** [nICEnnnnnnnLee/BilibiliLiveRecorder#30]
直接从虎牙拉取源后音频编码为he-aac v2 20k码率 如直传B站或其他视频平台将会被直接转换成20k的aac格式，会造成音频变成苏联解体音质，
目前解决方法：使用ffmpeg copy视频流 将音频转码为aac 128k
希望能够直接整合到里面来(虽然这样就需要调用外部了

**Comment by nICEnnnnnnnLee** [comment]
+ 这个不打算加进去。
+ 总的来说，这个项目的目的是录制能够正常播放的视频。  
在达到这个目标后，对视频的再加工不在考虑范围

**Comment by nICEnnnnnnnLee** [comment]
新增了plugin功能，你可以尝试一下自己写一个Runtime调用命令行进行ffmpeg转码的实现。
