### ISSUE TITLE
加载cookies出错

### ISSUE THREAD

**Issue by cairnechen** [nICEnnnnnnnLee/BilibiliLiveRecorder#31]
获取cookies工具——chrome扩展[cookies.txt ](https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg)

错误信息：
> douyu 直播录制 version v2.6.4
> 请输入房间号(直播网址是https://xxx.com/xxx，那么房间号就是xxx)
> 9999
> java.lang.ArrayIndexOutOfBoundsException: 1
>         at nicelee.bilibili.util.HttpCookies.convertCookies(HttpCookies.java:16)
>         at nicelee.bilibili.live.impl.RoomDealerDouyu.getRoomInfo(RoomDealerDouyu.java:55)
>         at nicelee.bilibili.Main.main(Main.java:229)
> 解析失败！！

**Comment by nICEnnnnnnnLee** [comment]
cookies 需要这样的格式：
```
dy_did=xxx; acf_did=xxx1; acf_auth=xxx; dy_auth=xxx; ...
```

**Comment by cairnechen** [comment]
> cookies 需要这样的格式：
> 
> ```
> dy_did=xxx; acf_did=xxx1; acf_auth=xxx; dy_auth=xxx; ...
> ```

有没有扩展能获取这种格式的cookies，之前用youtube-dl和you-get都是用cookies.txt

**Comment by cairnechen** [comment]
> cookies 需要这样的格式：
> 
> ```
> dy_did=xxx; acf_did=xxx1; acf_auth=xxx; dy_auth=xxx; ...
> ```

我通过F12 console document.cookie 复制了一段cookie，但保存后还是报同样的错误

**Comment by nICEnnnnnnnLee** [comment]
我这边没法复现...
你试试先抓一下退出登录或者隐私模式的cookie

**Comment by cairnechen** [comment]
> 我这边没法复现...
> 你试试先抓一下退出登录或者隐私模式的cookie

要不你用我的cookie试试
> dy_did=3069b72d1f09d8dc1cd3340a00071501; acf_did=3069b72d1f09d8dc1cd3340a00071501; smidV2=202002271619020c6eef488917fbea774526b2d8823c86004e0ebd95d719a40; acf_uid=677470; acf_username=auto_D75oTgHJGZ; acf_nickname=%E5%90%8C%E5%AD%A6%E5%8F%AB%E6%88%91%E8%8A%82%E5%88%B6; acf_own_room=1; acf_groupid=1; acf_phonestatus=1; acf_avatar=https%3A%2F%2Fapic.douyucdn.cn%2Fupload%2Favanew%2Fface%2F201803%2F26%2F18%2F068d25d47a6a4e301e0b91e9745fad26_; acf_ct=0; acf_ltkid=91406122; acf_biz=1; acf_stk=9fdf19ab8267d66b; acf_ccn=3dc61fbe38c5e3cc9685776801fc9ad6

**Comment by nICEnnnnnnnLee** [comment]
> 
> 
> > 我这边没法复现...
> > 你试试先抓一下退出登录或者隐私模式的cookie
> 
> 要不你用我的cookie试试
> 
> > dy_did=xxx...

+ 我这边好好的，没发现问题。。。
+ 另外，你把cookie信息给删除了吧
