### ISSUE TITLE
[Feature Request] Unattended recording

### ISSUE THREAD

**Issue by s-kk** [nICEnnnnnnnLee/BilibiliLiveRecorder#36]
Hello!
I've noticed that the current version of live recorder does not support unattended recording, which means you will have to start recording manually when a live starts. Is it possible to add support for unattended recording?  
That way we can simply run the java app and leave it for automatic recording start/stop.

Thanks a lot for helping!

**Comment by nICEnnnnnnnLee** [comment]
The app could periodically query the live status and start record if live is on. Here're the configurations related.

| Key  | -- | 
| ------------- | ------------- |  
| retryIfLiveOff  | `Bool.` Retry if the query result of live status is off. Default value: false | 
| maxRetryIfLiveOff  | `Int.` Max count of retry if the query result of live status is off. If 0 is set, the app will attemp to query and query again util the live is on. Default value: 0 | 
| retryAfterMinutes  | `Double.` The period between two query attempt. Default value: 5.0 |

**Comment by s-kk** [comment]
Thanks for replying! Also sorry I didn't see these options. I'll try them later.  
One more little suggestion: is it possible to read configuration file instead of typing them up every time? File types like ```json``` or ```yaml``` are very convenient. 

Thanks anyway for helping!

**Comment by nICEnnnnnnnLee** [comment]
In my view, the cost of edit of `json` or `yaml` somehow equals saving frequently-used commands to `.bat` or `.sh`; neverthless, I'll take it into consideration.😳

**Comment by s-kk** [comment]
I’ve tried the options mentioned above and seems that these options would only work if the live hasn’t started.  
If the live hasn’t started, the program would query live periodically. But if the live has already started and then ended, the program won’t query live anymore after the live ended.

**Comment by nICEnnnnnnnLee** [comment]
You could set `stopAfterOffline=false&retryIfLiveOff=true` if you wanna continue after a successful record event

**Comment by s-kk** [comment]
Thanks! That helps.
