### ISSUE TITLE
请教一下，如何保持链接

### ISSUE THREAD

**Issue by NeroArc** [nICEnnnnnnnLee/BilibiliLiveRecorder#4]
你好，想请教一下。我也想用Java写一个录制B站直播的程序，但是在实际过程中，通过API获取的链接在下载一段时间后就会断开。请问是如何保持持续链接的？我在看代码的时候看的并不是很明白，请问是否除了Java相关知识还需要哪些方面的知识呢？

**Comment by nICEnnnnnnnLee** [comment]
`通过API获取的链接在下载一段时间后就会断开` 这个一段时间是多久呢？

**Comment by NeroArc** [comment]
就如果我只通过API返回的第一个url去下载。这个一段时间并不固定，最短的时候7分钟就就断掉了，最长的话是57分钟左右。

**Comment by nICEnnnnnnnLee** [comment]
+ 这个我平时录制的时候一般就十来分钟，也不知道有没有这个问题😰
我的想法是：
+ 将网络连接的`ReadTimeout`时长设长一点；
+ 如果还不行，只能再重试连接了。

**Comment by nICEnnnnnnnLee** [comment]
想了下，跟浏览器播放直播的区别就在于：
+ webSocket连接了实时弹幕
+ 页面会周期性的发心跳包一样的东西

我想不太可能是这方面的问题，服务器那边应该没那么smart吧，毕竟增加工作量😳

**Comment by NeroArc** [comment]
你好厉害，这样就能想到。事实上，我通过控制台Network看的时候发现，确实周期性的发送心跳包。我之后再测试一下最长能持续多久的录制。此外想请教一下，我想按照你的项目造轮子，但是除了Java代码的部分，HTTP部分只能看懂大概，具体的实现仍不是很明白，请问我是需要补充HTTP相关的知识么？

**Comment by NeroArc** [comment]
你好厉害，这样就能想到。事实上，我通过控制台Network看的时候发现，确实间隔一定时间发送心跳包。但是我认为心跳包应该是为了计算银瓜子宝箱。我之后再测试一下最长能持续多久的录制。此外想请教一下，我想按照你的项目造轮子，但是除了Java代码的部分，HTTP部分只能看懂大概，具体的实现仍不是很明白，请问我是需要补充HTTP相关的知识么？

**Comment by nICEnnnnnnnLee** [comment]
就是在`HttpURLConnection`的基础上封装了一些常用的get/post请求。
我想你自己写个demo(比如下张图片下首歌)，再了解一些常见的反爬措施，应该就差不多了吧

**Comment by NeroArc** [comment]
好的，感谢您的热心回复。之后的测试是否支持最长时间录制我会在这个issue中反馈给您
