### ISSUE TITLE
虎牙直播录制结束后，无限处于“正在处理，请稍等 ”的状态

### ISSUE THREAD

**Issue by user741852** [nICEnnnnnnnLee/BilibiliLiveRecorder#45]
部分log：

已经录制了3h59m30s, 当前进度： 5.62 GB
已经录制了3h59m40s, 当前进度： 5.62 GB
下载完毕...
下载停止
处理文件中
正在处理，请稍等 
正在处理，请稍等 
正在处理，请稍等 
正在处理，请稍等 
正在处理，请稍等 
正在处理，请稍等 
正在处理，请稍等 
正在处理，请稍等 

此时，flv文件已经成功生成，part后缀名已消失。
请修复此bug。

**Comment by nICEnnnnnnnLee** [comment]
主程序一直等着输入stop 或 q停止。 算了，这个放到Daemon线程里
