### ISSUE TITLE
虎牙在开播一段时间后才能录制

### ISSUE THREAD

**Issue by nICEnnnnnnnLee** [nICEnnnnnnnLee/BilibiliLiveRecorder#5]
有朋友反馈在刚开播的时候会出现录制不上的情况，预计在开播后20分钟才能进行录制。

**Comment by nICEnnnnnnnLee** [comment]
本地不方便测试，目前猜测的可能有：
+ 部分信息是从`html`里面扣的，可能刷新不及时，导致： 
    + 刚开播直播状态未更新  
    + 或者播放源`json`未更新  
+ 为了方便，项目选取的是播放源`json`中`FLV`流，而没有考虑`M3U8/slice`，刚开播时虎牙未提供`FLV`流

求定位，求解决方案😳

**Comment by user741852** [comment]
刚开播时，jsonObject拿不到stream这个属性。

**Comment by user741852** [comment]
> 本地不方便测试，目前猜测的可能有：
> 
> * 部分信息是从`html`里面扣的，可能刷新不及时，导致：
>   
>   * 刚开播直播状态未更新
>   * 或者播放源`json`未更新
> * 为了方便，项目选取的是播放源`json`中`FLV`流，而没有考虑`M3U8/slice`，刚开播时虎牙未提供`FLV`流
> 
> 求定位，求解决方案😳

虎牙的startRecord那里为啥注释掉了m3u8？

**Comment by nICEnnnnnnnLee** [comment]
+ m3u8流的`.ts`文件下载以后怎么处理是个问题。
    + 如果直接文件拼接成一个大的ts文件，播放效果不是很好  
    + 如果自己再去解析转换，实现的工作量太大  
    + 如果调用ffmpeg，又要增加依赖  

===> 最后录制使用的是flv的流

**Comment by user741852** [comment]
> 
> 
>     * m3u8流的`.ts`文件下载以后怎么处理是个问题。
>       
>       * 如果直接文件拼接成一个大的ts文件，播放效果不是很好
>       * 如果自己再去解析转换，实现的工作量太大
>       * 如果调用ffmpeg，又要增加依赖
> 
> 
> ===> 最后录制使用的是flv的流

我没做过视频类的。请问为什么说合并成一个大的ts文件，播放效果不好？

**Comment by nICEnnnnnnnLee** [comment]
我本身对多媒体了解也不是很深入，这是我实现之后的感觉。
我试着合并过几个，但是播放时偶尔（尤其是拖拽进度后）可能会有一两秒花屏，把大的ts文件ffmpeg转成mp4后反而没有这个问题

**Comment by user741852** [comment]
> 
> 
> 我本身对多媒体了解也不是很深入，这是我实现之后的感觉。
> 我试着合并过几个，但是播放时偶尔（尤其是拖拽进度后）可能会有一两秒花屏，把大的ts文件ffmpeg转成mp4后反而没有这个问题
我查了一下，也有其他人遇到了类似问题。有一个解决方案说除了转格式，也可以使用MPV或SMPlayer播放器解决。要试试看？
https://mpv.io/
https://www.smplayer.info/

**Comment by nICEnnnnnnnLee** [comment]
如果要在指定类型的播放器上才能有良好的播放体验的话，这样做意义不大

**Comment by user741852** [comment]
> 
> 
> 如果要在指定类型的播放器上才能有良好的播放体验的话，这样做意义不大

但是如果不使用m3u8，怕是无法解决这个issue。我觉得可以作为一个实验性的功能先用起来。

**Comment by nICEnnnnnnnLee** [comment]
我再确认一下，你的意思是：
1. 刚开播的时候，可以从播放页面的html里：
    + 拿到`m3u8`源
    + 拿不到`flv`源
2. 二十来分钟之后，可以从播放页面的html里：
    + 拿到`m3u8`源
    + 拿到`flv`源
3. 前后从html里拿播放m3u8源的正则方式相同。

**Comment by user741852** [comment]
> 
> 
> 我再确认一下，你的意思是：
> 
>     1. 刚开播的时候，可以从播放页面的html里：
>        
>        * 拿到`m3u8`源
>        * 拿不到`flv`源
> 
>     2. 二十来分钟之后，可以从播放页面的html里：
>        
>        * 拿到`m3u8`源
>        * 拿到`flv`源
> 
>     3. 前后从html里拿播放m3u8源的正则方式相同。

不好意思，是我搞错了。。。我查看了刚开播时的html文件，里面既没有m3u8，也没有flv源。。。

**Comment by user741852** [comment]
突然想到，可否增加对这种情况的retry？

**Comment by lbcake** [comment]
> 突然想到，可否增加对这种情况的retry？

huya是否可以增加一个 单纯抓取flv源的插件 


目前想手动复制flv的流地址 添加至服务器下载   

用Greasy Fork上的的插件 获取的到流  有时候会出现下载失败的情况   还有时候下载出现几M 几kb的情况

作者能否帮忙解决一下

**Comment by ccbea** [comment]
虎牙刚开播没有低画质，因为设置的画质没有，脚本会直接提示退出

**Comment by lbcake** [comment]
> 虎牙刚开播没有低画质，因为设置的画质没有，脚本会直接提示退出

这个项目 录制前面会绿屏  早就弃用了

**Comment by ccbea** [comment]
> > 虎牙刚开播没有低画质，因为设置了画质，脚本会直接提示退出
> 
> 这个项目引起了前面会绿屏的拒绝用了

我的录出来效果还挺好

**Comment by ccbea** [comment]
看我提的issue
