### ISSUE TITLE
感谢开源贡献，请问能否增加抖音的直播录制功能！

### ISSUE THREAD

**Issue by geekyun7** [nICEnnnnnnnLee/BilibiliLiveRecorder#52]
首先感谢楼主的开源贡献
最近看到抖音一些人的直播很有价值
请问能否增加抖音的直播录制功能呢
十分感谢！！！

**Comment by persia7emily** [comment]
+1 这个工具真好用，以后不怕录屏录着卡机了，希望增加抖音直播，实在不想下载抖音
