### ISSUE TITLE
能添加一个保存.ts格式文件的选项吗？

### ISSUE THREAD

**Issue by daxiaamo** [nICEnnnnnnnLee/BilibiliLiveRecorder#57]
能添加一个保存.ts格式文件的选项吗？我尝试自己修改代码但是自己用IDEA无法成功打包。

**Comment by nICEnnnnnnnLee** [comment]
+ 添加配置举例
```
@Option(name = "saveAsTS", defaultValue = "false") 
 public static boolean saveAsTS; 

调用 Config.saveAsTS 即可
```
https://github.com/nICEnnnnnnnLee/BilibiliLiveRecorder/blob/2658f00e3928d2b00154af66ef3be6eec0497ab8/src/main/java/nicelee/bilibili/Config.java#L25-L30

<hr/>

+ 我看你的情况可以看作是额外写一个解析(目前都是`flv`的)
你可以参考[RoomDealerHuya](https://github.com/nICEnnnnnnnLee/BilibiliLiveRecorder/blob/master/src/main/java/nicelee/bilibili/live/impl/RoomDealerHuya.java)继承**nicelee.bilibili.live.RoomDealer**自己写一个解析器。  
    + 将liver改一下，改成{liver}_ts；再将返回type改成`.ts`；等等。。。
    + TS的话直接拼接在一起合成一个文件在很多播放器上效果不好，一般需要额外处理，比如ffmpeg等。但这就要引入额外的依赖，是件麻烦事，有flv用flv就好了。
https://github.com/nICEnnnnnnnLee/BilibiliLiveRecorder/blob/2658f00e3928d2b00154af66ef3be6eec0497ab8/src/main/java/nicelee/bilibili/live/impl/RoomDealerHuya.java#L22-L30

**Comment by nICEnnnnnnnLee** [comment]
如果你是指的打包失败的话，可以参考机器打包发布release的脚本
https://github.com/nICEnnnnnnnLee/BilibiliLiveRecorder/blob/2658f00e3928d2b00154af66ef3be6eec0497ab8/.github/workflows/release.yml#L49-L52
