### ISSUE TITLE
此程序 时间校正时间过长   外加录制的视频会花屏    仅测试了huya      建议多方优化

### ISSUE THREAD

**Issue by lbcake** [nICEnnnnnnnLee/BilibiliLiveRecorder#59]
此程序 时间校正时间过长   外加录制的视频会花屏    

仅测试了huya      建议多方优化

**Comment by nICEnnnnnnnLee** [comment]
+ **时间校正时间过长**，耗时操作大头是磁盘读写io和debug输出。  
前者已经加了buffer，后者debug可以关闭，不再打算投入更多精力进行优化了。  
+ **录制的视频会花屏**：  
    + 一般情况下，仅会有视频的前几帧可能出现，但我觉得这个能够接受，也不打算再改。  
    + 如果是前面正常，到某个时间开始不对头，建议尝试不同的设置组合分割文件：`splitScriptTags/splitAVHeaderTags`
    + 如果整部视频都是这种情况，或者前面都解决不了问题，这说明我写的解决方案并不适用于该视频，建议转ffmpeg进行处理。
+ 对于以上两个问题，一个解决方案是使用plugin功能调用第三方软件(比如ffmpeg)进行处理
    + 设置参数，不校正时间戳，启用plugin。`check=false&plugin=true`
    + 新建`plugin`文件夹，将调用实现放在里面，命名为`CustomOperation.java`
    + 这个具体怎么实现呢？有个现成的flv转mp4的供参考[flv2mp4](https://github.com/nICEnnnnnnnLee/BilibiliLiveRecorder/blob/master/plugin/CustomOperation.flv2mp4.java)
    + 或者你嫌弃这个仍然比较重，那么自己写个脚本，使用plugin调用它也是好的。
     `String cmd[] = { "cmd", "/c", "start", "你写的脚本.bat", 传入参数1, 传入参数2...};`

**Comment by nICEnnnnnnnLee** [comment]
关于录制直播，实现原理无非以下几种：
+ 录屏
+ 获取直播源地址
   下载直播视频raw(到这里其实就可以正常观看了，只是可能会有缺陷)
   对下载的视频进行处理
+ 获取直播源地址
   对直播源直接解析并保存(牛b，反正我看了是脑壳疼，不过出异常重新录制可以降低难度)

我使用的是第二种，并做了一种对下载完成后raw data的处理的实现方案。    
只能说对某些录制视频能用，不敢说优秀或者泛用。  
如果没有意外(毕竟爱会消失)，我将只会对`获取直播源地址`这一步进行维护。  
以上。
