### ISSUE TITLE
无法拖动时间轴

### ISSUE THREAD

**Issue by sodog01** [nICEnnnnnnnLee/BilibiliLiveRecorder#6]
下载好的视频怎么打开无法拖动时间轴，只能从头播放下去

**Comment by nICEnnnnnnnLee** [comment]
呃，我这边没碰到过:flushed: 。。。
 @sodog01 老铁，能提供更详细一点的信息么： 
+ 系统环境和java版本
+ 使用的程序版本号，是不是Release最新的
+ 录制的是哪一个网站，当然能提供房间号更好
+ 是不是所有下载的视频都无法拖动，还是个别的。按照固定操作能不能复现
+ 使用的是什么播放器？换个播放器是否还是这样？
+ 有没有使用`时间戳校正`功能？视频的时间长度和录制的时长相比正不正常？
+ 视频的大小有多大？拖动的时间轴是否靠近结束
<hr/>

+ 对于已经录制完的视频，可以尝试使用`ffmpeg`转成MP4抢救一下，看看效果。
```
ffmpeg -i "sample.flv" -vcodec copy -acodec copy "sample.mp4"
```

**Comment by sodog01** [comment]
录制完的文件后缀有.part的文件，我主动去掉这个后缀的视频文件就会无法拖动时间轴，还有个问题，录制的直播，如果主播卡会导致录制的视频音画不同步。

**Comment by sodog01** [comment]
用你这个命令转换后，能拖动时间轴了，但是画面是停止在拖动前的，只有声音到。把文件拖到checkFlv.bat打开之后的视频文件旧可以正常拖动时间轴了。
这些出问题的视频文件都是因为主播卡自动断录制导致的

**Comment by nICEnnnnnnnLee** [comment]
+ 如果带有`.part`后缀，那就是没有处理的原始文件。 一般来讲是下载时候因为异常中断导致没有后续处理造成的。
+ 原始文件有两个缺陷：
    + 由于录制停止的时机不同，可能导致最后一帧不完整。  
         + **直观来讲**，就是从文件头开始计算时间没有问题，但是**从文件尾部开始**计算不出来。
    + 时间戳与服务器推流同步，导致视频时间长度有问题
         + 部分播放器计算时长为`最后的时间戳 - 0`
         + **直观来讲**，可能有的播放器播放时画面没有问题，但是**视频时长不对劲**
+ **解决方案**
    + 已经下载的视频 - 校正时间戳  
`java -Dfile.encoding=utf-8 -cp BiliLiveRecorder.jar nicelee.bilibili.live.FlvChecker "文件路径"`

**Comment by nICEnnnnnnnLee** [comment]
@sodog01 是最新版本么？是的话我再看看程序本身的异常处理有木有问题:flushed:

**Comment by sodog01** [comment]
校正时间戳需要加回.part后缀吗？ 之前是用1.6版本的，昨天看到有1.7版本

**Comment by nICEnnnnnnnLee** [comment]
不用，就是`.flv`。

**Comment by sodog01** [comment]
可以拖动时间轴了，但是音画不同步，估计是录制的时候就有，能录制的时候不会因为线路卡而导致音画不同步吗？

**Comment by nICEnnnnnnnLee** [comment]
+ 音画不同步有两种情况，录制的时候参数选择不删除源文件`delete=false`： 
    1. **源文件** 音画同步，**校正后文件** 音画不同步，我再想办法处理处理   
    2. **源文件** 音画不同步，**校正后文件** 音画不同步，这很可能是播放源的问题，涉及到更复杂的多媒体处理，无能为力
