### ISSUE TITLE
下载源代码编译失败

### ISSUE THREAD

**Issue by Leonhardt92** [nICEnnnnnnnLee/BilibiliLiveRecorder#62]
作者您好, 感谢您分享了这个
      我下载您的代码之后, 在idea里的maven找到项目, 能帮忙解答一下吗?
![image](https://user-images.githubusercontent.com/35802996/120752040-8df02500-c53b-11eb-9180-a5db1201f989.png)

尝试过如下操作:

1. 修改maven的setting.xml, 试过maven.aliyun.com, repo.maven.apache.org 以及 https://maven.pkg.github.com/nICEnnnnnnnLee/BilibiliLiveRecorder  镜像都是下载不到jar包

期待您的解答, 祝你工作顺利, 身体健康

**Comment by nICEnnnnnnnLee** [comment]
![火狐截图_2021-08-16T12-20-36 020Z](https://user-images.githubusercontent.com/19970934/129562905-78f5e748-96c3-448b-aa2a-ac51a9ccd29b.png)

<https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#authenticating-with-a-personal-access-token>
