### ISSUE TITLE
请求快手直播信息中不带cookie会报错，返回请求中被认定机器人

### ISSUE THREAD

**Issue by bookjiang** [nICEnnnnnnnLee/BilibiliLiveRecorder#63]
不知道是不是个例，RoomDealerKuaishou类中，getLiveInfoObj()方法中获得直播信息的json时也带上cookie就可以获得直播信息，否则被认定为机器人

**Comment by nICEnnnnnnnLee** [comment]
![火狐截图_2021-08-16T12-35-07 276Z](https://user-images.githubusercontent.com/19970934/129564613-aac906fa-11ee-47f0-b291-2b6c224727c5.png)

+ 不带cookie可能会是成功的，因为项目里面本来就带了一个cookie，但公共的应该很容易失效。
+ 你需要一个过了拖拽验证码的cookie才能获取直播间的详细信息。
+ cookie生效与否只影响直播间信息的获取，**不影响直播流的获取与下载**

**Comment by bookjiang** [comment]
哦哦，谢谢
