### ISSUE TITLE
虎牙录播模块录制M3U8有问题. 

### ISSUE THREAD

**Issue by SuperOnee** [nICEnnnnnnnLee/BilibiliLiveRecorder#64]
在录制M3U8的时候出现 服务器那边返回 403....

**Comment by nICEnnnnnnnLee** [comment]
为了便于处理，本项目的所有源都用的是FLV，并没有使用M3U8流

**Comment by SuperOnee** [comment]
> 为了便于处理，本项目的所有源都用的是FLV，并没有使用M3U8流

大佬, 有没有什么办法能录制成MP4格式的呢
