### ISSUE TITLE
请问可以增加手动停止录制后继续保持监控的功能吗？

### ISSUE THREAD

**Issue by HexStan** [nICEnnnnnnnLee/BilibiliLiveRecorder#66]
想要在输入stop结束录制后，程序不退出，继续检测直播间的状态，等待下次开播时自动录制。

**Comment by nICEnnnnnnnLee** [comment]
我想我没明白你的意思？

主播下播后，程序会自动停止录制，而不必输入stop；主播没下播，你输入stop，又想要继续监控，这是还是会继续录播，那为什么要输入stop呢？

**Comment by nICEnnnnnnnLee** [comment]
目前程序实现了一个简单的轮询直播监控，可以在开播后不久进行录制；也支持主播下播后继续监听。
具体配置请参考`readme`的参数说明列表

**Comment by HexStan** [comment]
> 我想我没明白你的意思？
> 
> 主播下播后，程序会自动停止录制，而不必输入stop；主播没下播，你输入stop，又想要继续监控，这时还是会继续录播，那为什么要输入stop呢？

我的部分配置如下：
`"stopAfterOffline": false,
"retryIfLiveOff": true,
"retryAfterMinutes": 0.1,
"failRetryAfterMinutes": 0.1`

我的意思是，我想要当主播在播时，我输入stop后不是直接退出程序，而是只结束对本场直播的录制。此时程序就是一个只轮询不录制的状态。当主播下次开播时重新启动录制。

用一句话来说就是：在手动停止录制后程序进入只轮询不录制的状态。

**Comment by nICEnnnnnnnLee** [comment]
这不在考虑范围内，你可以写个脚本延迟启动程序
