### ISSUE TITLE
请问是否支持下播后一直监听状态

### ISSUE THREAD

**Issue by retroxz** [nICEnnnnnnnLee/BilibiliLiveRecorder#82]
目前配置了stopAfterOffline retryIfLiveOff和retryAfterMinutes shell命令如下
`java -Dfile.encoding=utf-8 -jar BiliLiveRecorder.jar "debug=false&check=false&liver=bili&id=22603245&saveFolder=D:/record&retryIfLiveOff=true&maxRetryIfLiveOff=0&retryAfterMinutes=0.5&qn=-1&fileName={startTime}-{seq}&fileSize=4000&stopAfterOffline=false"`

现在下播处理完录播文件之后 程序依然会停止运行
请问如何配置能达到下播后继续监听的效果

**Comment by ccbea** [comment]
我这样是可以的: 
cd /d %~dp0
java -Dfile.encoding=utf-8 -jar BiliLiveRecorder.jar "debug=false&check=false&delete=true&liver=huya&id=520531&qn=-1&options=H:\BilibiliLiveRecord.v2.16.0\1.json&filePeriod=30&stopAfterOffline=false&retryIfLiveOff=true&maxRetryIfLiveOff=0&retryAfterMinutes=5.0&failRetryAfterMinutes=1&retry=9999"
