### ISSUE TITLE
抖音网页版的cookie问题

### ISSUE THREAD

**Issue by qchenac** [nICEnnnnnnnLee/BilibiliLiveRecorder#84]
我用get cookies的插件获得的cookie转成要求的格式后还是报错，另外如下图用开发者模式抓包文件头里也没有cookie，求大佬指点
<img width="849" alt="Screen Shot 2022-05-17 at 19 42 17" src="https://user-images.githubusercontent.com/1908759/168803317-06a46da9-f447-4cf9-8d2d-150ea2967ea2.png">

**Comment by qchenac** [comment]
<img width="578" alt="Screen Shot 2022-05-17 at 19 47 34" src="https://user-images.githubusercontent.com/1908759/168803908-8e68e2aa-435a-40cc-b361-9323fd295fbf.png">
这是get cookies插件获取的cookie格式，我是只取name和value做成支持的格式，比如ttwid=xxxx;

**Comment by nICEnnnnnnnLee** [comment]
> 另外如下图用开发者模式抓包文件头里也没有cookie


你应该拦截一条`https://live.douyin.com/...`的网络请求进行观察。

**Comment by qchenac** [comment]
可以了，是我的问题。犯了两个错，一个就是作者提到的应该监视`https://live.douyin.com/webcast/assets/effects/?aid=...`这种链接，二一个是douyin-cookie.txt的位置需要是当前运行的目录，而不是jar所在的目录。再次感谢作者！
