### ISSUE TITLE
批量执行多个录制时初始化出错

### ISSUE THREAD

**Issue by MYJN** [nICEnnnnnnnLee/BilibiliLiveRecorder#89]
java -Dfile.encoding=utf-8 -jar BiliLiveRecorder.jar "debug=false&check=true&liver=kuaishou&id=*****&qn=o&retry=5&stopAfterOffline=false&retryIfLiveOff=true&maxRetryIfLiveOff=0&retryAfterMinutes=5.0&failRetryAfterMinutes=1.0" 
pause

Error occurred during initialization of VM
Unable to allocate 196544KB bitmaps for parallel garbage collection for the requested 6289408KB heap.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

目前有12个录制启动脚本,当批量执行到第6个的时候开始出现初始化错误,无法正常开始执行

**Comment by nICEnnnnnnnLee** [comment]
程序在设计的时候并没有考虑多个录制的问题，这导致同时开启多个的话会有很多不必要的重复开销。

目前也没打算重构。

直播录制实质上就是`获取直播源` + `下载直播源(FLV)` + `处理下载的raw文件`。  
本项目除了提供了一个现成的解决方案以外，还提供了上述三个步骤的相关API，你可以参考[此处](https://github.com/nICEnnnnnnnLee/BilibiliLiveRecorder/blob/master/DOC.md)自己进行实现。
