### ISSUE TITLE
如何录制过程中能否按时间或者大小将视频分段，录制视频太大

### ISSUE THREAD

**Issue by yslinwe** [nICEnnnnnnnLee/BilibiliLiveRecorder#9]

**Comment by nICEnnnnnnnLee** [comment]
不是很理解这种使用场景诶，就算分段大小也还是很大啊

**Comment by yslinwe** [comment]
是因为我在上传视频的时候，网站或者网盘有文件大小的限制。

**Comment by nICEnnnnnnnLee** [comment]
+ [V2.0]新特性使用方式举例： 
    + java -Dfile.encoding=utf-8 -jar BiliLiveRecorder.jar "debug=false&check=false&delete=false&liver=douyu&id=233233&qn=0&**fileSize=100**"
+ 如果fileSize=100，那么录制的文件大小会比100MB要稍大，但不会超过最近10s的下载量。
+ 如果filePeriod=30，那么录制的文件时长会比30min稍长，但不会超过10s

**Comment by yslinwe** [comment]
感谢

**Comment by yslinwe** [comment]
没有v2.0的BiliLiveRecorder.jar，该怎么运行

**Comment by nICEnnnnnnnLee** [comment]
我没明白你的意思？

**Comment by yslinwe** [comment]
运行java -Dfile.encoding=utf-8 -jar BiliLiveRecorder.jar "debug=false&check=false&delete=false&liver=douyu&id=233233&qn=0&fileSize=100“ 命令
时 报Error: Unable to access jarfile BiliLiveRecorder.jar

**Comment by nICEnnnnnnnLee** [comment]
我楞了很久，打了很多字，然后删除了。    
亲，先cd 到jar包所在目录。

**Comment by yslinwe** [comment]
我运行虎牙的bat时
java.lang.NullPointerException
        at nicelee.bilibili.Main.getRoomDealer(Main.java:211)
        at nicelee.bilibili.Main.main(Main.java:93)
当前没有发现合适的视频录制器： huya

**Comment by nICEnnnnnnnLee** [comment]
请确认一下版本号，最近几个版本这个异常都不应该在第211行和93行

**Comment by yslinwe** [comment]
显示的是huya 直播录制 version v1.4
