### ISSUE TITLE
监控直播,开头录制画面是花屏的

### ISSUE THREAD

**Issue by MYJN** [nICEnnnnnnnLee/BilibiliLiveRecorder#91]
花屏画面持续时间 00:00:00-00:00:03

java -Dfile.encoding=utf-8 -jar BiliLiveRecorder.jar "debug=false&check=true&liver=kuaishou&id=***&qn=0&retry=5&stopAfterOffline=false&retryIfLiveOff=true&maxRetryIfLiveOff=0&retryAfterMinutes=5.0&failRetryAfterMinutes=1.0" 

-----------------------------
![NVIotRTmf3](https://user-images.githubusercontent.com/13313477/190965009-3c53ea4f-1054-4edb-bd1c-44bccaac24b0.png)

**Comment by nICEnnnnnnnLee** [comment]
不太想为这个问题大动干戈，如果只有几秒的花屏的话请自行处理
