### ISSUE TITLE
YY直播解析失败

### ISSUE THREAD

**Issue by luyu911** [nICEnnnnnnnLee/BilibiliLiveRecorder#94]
目前排查到的原因主要有两个：一个是http协议现在会自动301跳转到https，所以html获取失败。还有一个是livingStream现在无法从html中获取了，好像是做了比较复杂的加密，还没找到解决办法。

**Comment by luyu911** [comment]
直播流可以通过移动平台接口抓取

`fetch("https://interface.yy.com/hls/new/get/房间id/房间id/2000?source=wapyy&callback=jsonp2",{
    header: {
        'user-agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1',
        'referer': 'https://wap.yy.com',
    },
    json: false
})`

**Comment by luyu911** [comment]
房间信息接口

`fetch("https://wap.yy.com/mobileweb/play/liveinfo?sid=房间id&ssid=房间id",{
    header: {
        'user-agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1',
        'referer': 'https://wap.yy.com',
    },
    json: false
})`

**Comment by luyu911** [comment]
其中比较重要的是 referer': 'https://wap.yy.com'，否则会返回hls 404

**Comment by nICEnnnnnnnLee** [comment]
移动平台接口的直播流为m3u8，这里换了一种解析方式
