### ISSUE TITLE
用douyin2解析的，没在直播的提示没直播，在直播的就报错

### ISSUE THREAD

**Issue by woliuguojian** [nICEnnnnnnnLee/BilibiliLiveRecorder#96]
root@DiskStation:/volume2/tools/BilibiliLiveRecord.v2.21.0# java -Dfile.encoding=utf-8 -jar BiliLiveRecorder.jar "debug=true&check=true&liver=douyin2&"
douyin2 直播录制 version v2.21.0
请输入房间号(直播网址是https://xxx.com/xxx，那么房间号就是xxx)
930059835502
RoomDealerDouyin-getLiveDataByShortId/177 : {"data":{"message":"系统繁忙，请稍后再试","prompts":"系统繁忙，请稍后再试"},"extra":{"now":1665948563931},"status_code":10037}
org.json.JSONException: JSONObject["user"] not found.
        at org.json.JSONObject.get(JSONObject.java:573)
        at org.json.JSONObject.getJSONObject(JSONObject.java:766)
        at nicelee.bilibili.live.impl.RoomDealerDouyin.getRoomInfo(RoomDealerDouyin.java:90)
        at nicelee.bilibili.Main.getRoomInfo(Main.java:153)
        at nicelee.bilibili.Main.main(Main.java:86)
抖音需要cookie, 请确认cookie是否存在或失效
解析失败！！

**Comment by Eriice** [comment]
同报错，在 win 或者 mac 上都是一致的错误行为。
使用 liver=douyin 报错 JSONObject["anchor"] not found
使用 liver=douyin2 报错 JSONObject["user"] not found
未登录cookie （已过拖拽）、已登录cookie 均相同的错误行为。

**Comment by woliuguojian** [comment]
ok了，encodeuri就好了

**Comment by Eriice** [comment]
> 



> 把你们的cookie在控制台里用`encodeURI`转一下，浏览器它**~有时候~**呈现的cookie和抓包不太一致 `ttwid=1%7C0CRNQycblK_U-M2...` √ `ttwid=1|0CRNQycblK_U-M2...` ×

没问题，感谢
