### ISSUE TITLE
请问日志如何不打印

### ISSUE THREAD

**Issue by insoxin** [nICEnnnnnnnLee/BilibiliLiveRecorder#99]
不重要的这些信息 这些有点多啊

已经录制了0m10s, 当前进度： 12.28 MB
已经录制了0m20s, 当前进度： 22.05 MB
已经录制了0m30s, 当前进度： 31.86 MB
已经录制了0m40s, 当前进度： 41.47 MB
已经录制了0m50s, 当前进度： 51.28 MB
已经录制了1m0s, 当前进度： 60.88 MB
已经录制了1m10s, 当前进度： 70.81 MB
已经录制了1m20s, 当前进度： 80.49 MB
已经录制了1m30s, 当前进度： 90.28 MB
已经录制了1m40s, 当前进度： 100.05 MB

**Comment by nICEnnnnnnnLee** [comment]
+ 要么windows `>nul` , linux `> /dev/null`, `Ctrl + C`退出
+ 要么自己改代码
https://github.com/nICEnnnnnnnLee/BilibiliLiveRecorder/blob/bf1649b8398b1c66d7b9cf09c17de854fbf51885/src/main/java/nicelee/bilibili/threads/ThMonitor.java#L61-L73
